[versions]
minecraft = "1.21.11"
paper = "1.21.11"
hikaricp = "7.0.2"

[libraries]
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }
clickhouse-jdbc = { group = "com.clickhouse", name = "clickhouse-jdbc", version = "0.8.5" }
bstats = { group = "org.bstats", name = "bstats-bukkit", version = "3.1.0" }
